[files]
extend-exclude = [
{% if cookiecutter.include_cpp %}
    "fmt",
    "minhook",
    "pybind11",
{% endif %}
    "LICENSE",
    ".typos.toml"
]

{% if cookiecutter.include_cpp %}
[default.extend-identifiers]
llibgcc_s_seh = "llibgcc_s_seh"
{% endif %}

[default.extend-words]
UE = "UE"
