[files]
extend-exclude = [
{% if cookiecutter.include_cpp %}
    "fmt",
    "minhook",
    "pybind11",
{% endif %}
    "LICENSE",
    ".typos.toml"
]

[default]
extend-ignore-re = [
    # Ignore markdown links to github commits/trees
    "\\[[0-9a-fA-F]+?\\]\\(https://github.com/.+?/.+?/(commit|tree)/.+?\\)",
]

{% if cookiecutter.include_cpp %}
[default.extend-identifiers]
llibgcc_s_seh = "llibgcc_s_seh"
{% endif %}

[default.extend-words]
UE = "UE"
