name: Rebuild containers
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container: [
          "clang-cross",
          "llvm-mingw",
          "mingw",
        ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/bl-sdk/${{ matrix.container }}
          cacheFrom: ghcr.io/bl-sdk/${{ matrix.container }}
          configFile: "{{ cookiecutter.__project_slug }}/.devcontainer/${{ matrix.container }}/devcontainer.json"
          push: always
